config/routes.rb
Rails.application.routes.draw do
  root "listings#index"
  devise_for :users
  resources :listings

  get '/support' => 'support#new'
  post '/support' => 'support#create'

  post '/bookings' => 'bookings#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :listing
  belongs_to :guest

  validate :validate_dates

  private
    def validate_dates
      errors.add(:check_in_date, 'can\'t be in the past') if check_in_date < Date.today
      errors.add(:check_out_date, 'can\'t be before check in date') if check_out_date <= check_in_date
    end
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :listing
  has_many :users
  has_many :messages
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :country, presence: {
    meesage: -> (listing, data) { "No country code for #{listing.country_code} "}
  }
  geocoded_by :full_address
  after_validation :geocode

  def country
    ISO3166::Country.new(country_code.upcase)
  end

  def full_address
    "#{street_address}, #{city}, #{country}"
  end

  def cents_to_dollars(cents)
    Money.new(cents, "AUD").format
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :conversations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    booking_params = params.require(:booking).permit(:check_in_date, :check_out_date, :guest_count)
    booking = Booking.new(booking_params)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
    @night_fee_cents = @listing.night_fee_cents
    @cleaning_fee_cents = @listing.cleaning_fee_cents
    @new_booking = Booking.new(check_in_date: Date.today)
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:title, :street_address, :city, :country_code, :bed_count, :bedroom_count, :bathroom_count, :description, :night_fee_cents, :cleaning_fee_cents)
    end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def new
    @error_messages = []
  end

  def create
    from_email = params[:email]
    message = params[:message]
    
    @error_messages = []
    @error_messages << 'Please enter your email' if from_email.empty?
    @error_messages << 'Please enter your message' if message.empty?

    #No errors, all good
    if @error_messages.empty?
      #Send the message to our support email address
      SupportMailer.contact_support(from_email, message).deliver_now
      #Show success message
      render :success
    #There are errorss
    else
      #Show the user the errors
      render :new
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBnb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :listing_title %>
  </div>

  <div class="field">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, id: :listing_street_address %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :listing_city %>
  </div>

  <div class="field">
    <%= form.label :country_code %>
    <%= form.text_field :country_code, id: :listing_country_code %>
  </div>

  <div class="field">
    <%= form.label :bed_count %>
    <%= form.number_field :bed_count, id: :listing_bed_count %>
  </div>

  <div class="field">
    <%= form.label :bedroom_count %>
    <%= form.number_field :bedroom_count, id: :listing_bedroom_count %>
  </div>

  <div class="field">
    <%= form.label :bathroom_count %>
    <%= form.number_field :bathroom_count, id: :listing_bathroom_count %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :listing_description %>
  </div>

  <div class="field">
    <%= form.label :night_fee_cents %>
    <%= form.number_field :night_fee_cents, id: :listing_night_fee_cents %>
  </div>

  <div class="field">
    <%= form.label :cleaning_fee_cents %>
    <%= form.number_field :cleaning_fee_cents, id: :listing_cleaning_fee_cents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Street address</th>
      <th>City</th>
      <th>Country</th>
      <th>Bed count</th>
      <th>Bedroom count</th>
      <th>Bathroom count</th>
      <th>Description</th>
      <th>Night fee cents</th>
      <th>Cleaning fee cents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.title %></td>
        <td><%= listing.street_address %></td>
        <td><%= listing.city %></td>
        <td><%= listing.country.name %></td>
        <td><%= listing.bed_count %></td>
        <td><%= listing.bedroom_count %></td>
        <td><%= listing.bathroom_count %></td>
        <td><%= listing.description %></td>
        <td><%= listing.night_fee_cents %></td>
        <td><%= listing.cleaning_fee_cents %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<h1>
  <%= @listing.title %>
</h1>

<h2>Book</h2>
<p>
  <%= @listing.cents_to_dollars(@night_fee_cents) %> per night
</p>
<%= form_with(model: @new_booking, local: true) do |f| %>
  <div>
    <%= f.label :check_in_date, 'Check in:' %>
    <%= f.date_field :check_in_date %>
  </div>

  <div>
    <%= f.label :check_out_date, 'Check out:' %>
    <%= f.date_field :check_out_date %>
  </div>

  <div>
    <%= f.label :guest_count %>
    <%= f.number_field :guest_count %>
  </div>

  <%= f.button 'Book' %>

<% end %>


<p>
  <strong>Street address:</strong>
  <%= @listing.street_address %>
</p>

<p>
  <strong>City:</strong>
  <%= @listing.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @listing.country.name %>
</p>

<p>
  <strong>Coords:</strong>
  <%= @listing.latitude %>, <%= @listing.longitude %>
</p>

<p>
  <strong>Bed count:</strong>
  <%= @listing.bed_count %>
</p>

<p>
  <strong>Bedroom count:</strong>
  <%= @listing.bedroom_count %>
</p>

<p>
  <strong>Bathroom count:</strong>
  <%= @listing.bathroom_count %>
</p>

<p>
  <strong>Description:</strong>
  <%= @listing.description %>
</p>

<p>
  <strong>Cleaning fee cents:</strong>
  <%= @listing.cents_to_dollars(@cleaning_fee_cents) %>
</p>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/support/new.html.erb
<h1>Support</h1>

<p>Please message our support team here:</p>

<%= form_with(url: support_url, local: true) do |f| %>
  <% unless @error_messages.empty? %>
    <% @error_messages.each do |message| %>
      <p><%= message %></p>
    <% end %>
  <% end %>

  <div> 
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>

  <div> 
    <%= f.label :message %>
    <%= f.text_area :message, rows: 6 %>
  </div>  

  <%= f.button 'Send' %>
<% end %>

app/views/support/success.html.erb
<h1>Support</h1>

<p>Your message has been successfully received</p>